
GET  http://localhost:3000/api
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhdmlkIiwiaWF0IjoxNjIwMTczMzk4LCJleHAiOjE2MjAxNzM2OTh9.sOC6zCi-jBelqaxFQb1USu8072J_cv4e575AlnsKuxw
